# Generated by Django 4.2.6 on 2023-12-21 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 10, 14, 48, 151754, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 10, 14, 48, 151754, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 10, 14, 48, 151754, tzinfo=datetime.timezone.utc)),
        ),
    ]
